services:
  wordpress:
    image: ${DOCKERHUB_USERNAME}/b2b-oto:latest
    container_name: sanoto-wordpress
    restart: unless-stopped

    entrypoint: ["/bin/sh", "-lc"]
    command: >
      mkdir -p
      /var/www/html/web/app/uploads
      /var/www/html/web/app/cache/acorn/framework/views
      /var/www/html/web/app/cache/acorn/framework/cache
      /var/www/html/web/app/cache/acorn/framework/sessions
      &&
      chown -R www-data:www-data
      /var/www/html/web/app/uploads
      /var/www/html/web/app/cache
      &&
      apache2-foreground

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - ./runtime.env

    ports:
      - "${APP_PORT:-8001}:80"

    volumes:
      - ./app.env:/var/www/html/.env:ro
      - uploads_data:/var/www/html/web/app/uploads
      - cache_data:/var/www/html/web/app/cache

volumes:
  uploads_data:
  cache_data: